# Generated by Django 3.2.7 on 2022-05-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id_his', models.AutoField(primary_key=True, serialize=False)),
                ('NomePacOf', models.CharField(max_length=255, verbose_name='Nome do Paciente')),
                ('dt_VagaOf', models.DateField(verbose_name='Data')),
                ('h_VagaOf', models.TimeField(verbose_name='Hora')),
                ('procedimento', models.CharField(max_length=255, verbose_name='Procedimento')),
                ('dt_Inclusao', models.DateField(auto_now_add=True, null=True, verbose_name='Data da Inclusão')),
                ('UnidExec', models.CharField(max_length=255, verbose_name='Unidade Executante')),
                ('Motivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.CharField(max_length=19, unique=True, verbose_name='Cartao Sus')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('dataNascto', models.DateField(verbose_name='Data de Nascimento')),
                ('altura', models.CharField(max_length=4, verbose_name='Altura')),
                ('peso', models.CharField(max_length=6, verbose_name='Peso')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Exame'), ('2', 'Consulta')], max_length=10, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=7, verbose_name='Codigo do CNES')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidSolic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=7, verbose_name='Codigo do CNES')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='VagaOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_VagaOf', models.DateField(verbose_name='Data')),
                ('h_VagaOf', models.TimeField(verbose_name='Hora')),
                ('dt_Inclusao', models.DateField(auto_now_add=True, null=True, verbose_name='Data da Inclusão')),
                ('Motivo', models.CharField(max_length=100)),
                ('solicitacao', models.CharField(max_length=12, verbose_name='Código da Solicitação')),
                ('Paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.paciente', verbose_name='Nome do Paciente')),
                ('Procedimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.procedimento', verbose_name='Procedimento')),
                ('UnidExec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.unidexec', verbose_name='Unidade Executante')),
            ],
        ),
        migrations.CreateModel(
            name='VagaAg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=3, verbose_name='CID')),
                ('status', models.CharField(choices=[('1', 'Agendado'), ('2', 'Pendente')], max_length=255, verbose_name='Status')),
                ('Paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.paciente', verbose_name='Paciente')),
                ('VagaOf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.vagaof', verbose_name='Vaga Ofertada')),
            ],
        ),
    ]
