# Generated by Django 3.2.7 on 2022-05-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='tipo',
            field=models.CharField(choices=[('Exame', 'Exame'), ('Consulta', 'Consulta')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vagaag',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.paciente', verbose_name='Paciente Para Agendar'),
        ),
        migrations.AlterField(
            model_name='vagaag',
            name='VagaOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.vagaof', verbose_name='Vaga Ofertada por'),
        ),
    ]
