# Generated by Django 3.2.7 on 2022-06-27 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20220521_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_VagaOf', models.DateField(verbose_name='Data')),
                ('h_VagaOf', models.TimeField(verbose_name='Hora')),
                ('procedimento', models.CharField(max_length=255, verbose_name='Procedimento')),
                ('dt_Inclusao', models.DateField(auto_now_add=True, null=True, verbose_name='Data da Inclusão')),
                ('UnidExec', models.CharField(max_length=255, verbose_name='Unidade Executante')),
                ('Motivo', models.CharField(max_length=255)),
                ('NomePacAg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.paciente', verbose_name='Paciente Para Agendar')),
                ('NomePacOf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.vagaof')),
            ],
        ),
        migrations.DeleteModel(
            name='historico',
        ),
        migrations.DeleteModel(
            name='VagaAg',
        ),
    ]
