# Generated by Django 3.2.7 on 2022-07-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20220701_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeExecutante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=7, verbose_name='Codigo do CNES')),
                ('nome', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSolicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=7, verbose_name='Codigo do CNES')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VagaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vagaOfertada', models.DateField(verbose_name='Data')),
                ('hora_vagaOfertada', models.TimeField(verbose_name='Hora')),
                ('data_inclusao', models.DateField(auto_now_add=True, null=True, verbose_name='Data da Inclusão')),
                ('motivo', models.CharField(max_length=100)),
                ('solicitacao', models.CharField(max_length=12, verbose_name='Código da Solicitação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnidSolic',
        ),
        migrations.RemoveField(
            model_name='vagaof',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='vagaof',
            name='Procedimento',
        ),
        migrations.RemoveField(
            model_name='vagaof',
            name='UnidExec',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='dataNascto',
            new_name='dataNascimento',
        ),
        migrations.RenameField(
            model_name='permuta',
            old_name='dt_Inclusao',
            new_name='data_inclusao',
        ),
        migrations.RenameField(
            model_name='permuta',
            old_name='dt_VagaOf',
            new_name='data_vagaOfertada',
        ),
        migrations.RenameField(
            model_name='permuta',
            old_name='h_VagaOf',
            new_name='hora_vagaOfertada',
        ),
        migrations.RenameField(
            model_name='permuta',
            old_name='Motivo',
            new_name='motivo',
        ),
        migrations.RenameField(
            model_name='permuta',
            old_name='UnidExec',
            new_name='unidadeExecutante',
        ),
        migrations.RemoveField(
            model_name='permuta',
            name='NomePacAg',
        ),
        migrations.RemoveField(
            model_name='permuta',
            name='NomePacOf',
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='permuta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-01 07:25:17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permuta',
            name='nomePacienteAgendado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.paciente', verbose_name='Paciente Para Agendar'),
        ),
        migrations.AddField(
            model_name='permuta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-13 07:25:17.808062+00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Exame', 'Exame'), ('Consulta', 'Consulta')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='UnidExec',
        ),
        migrations.DeleteModel(
            name='VagaOf',
        ),
        migrations.AddField(
            model_name='vagaofertada',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.paciente', verbose_name='Nome do Paciente'),
        ),
        migrations.AddField(
            model_name='vagaofertada',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.procedimento', verbose_name='Procedimento'),
        ),
        migrations.AddField(
            model_name='vagaofertada',
            name='unidadeExecutante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.unidadeexecutante', verbose_name='Unidade Executante'),
        ),
        migrations.AddField(
            model_name='permuta',
            name='nomePacienteOfertado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.vagaofertada'),
        ),
    ]
