# Generated by Django 3.2.7 on 2022-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20220701_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagaofertada',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
