# Generated by Django 3.2.7 on 2022-07-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20220705_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagaofertada',
            name='unidadeSolicitante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadesolicitante'),
        ),
    ]
