# Generated by Django 3.2.7 on 2022-07-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_vagaofertada_unidadesolicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='vagaofertada',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Exame', 'Exame'), ('Consulta', 'Consulta')], max_length=10, verbose_name='Tipo'),
        ),
    ]
