# Generated by Django 3.2.7 on 2022-07-08 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0011_auto_20220708_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagaofertada',
            name='createdBy_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
