# Generated by Django 3.2.7 on 2022-07-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_auto_20220712_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadesolicitante',
            name='user',
        ),
    ]
