# Generated by Django 3.2.7 on 2022-07-12 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20220712_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userunidade',
            name='unidadeSolicitante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadesolicitante', verbose_name='Local de Trabalho'),
        ),
    ]
