# Generated by Django 3.2.7 on 2022-07-13 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0021_alter_unidadesolicitante_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userunidade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
    ]
