# Generated by Django 3.2.7 on 2022-07-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_auto_20220712_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadesolicitante',
            name='user',
        ),
    ]
